project_id = "osgrjouxwpnokfvzztji"

[functions.vimeo-sync]
verify_jwt = false

[functions.wp-oauth]
verify_jwt = false

[functions.digimember]
verify_jwt = false

[functions.assistant-chat]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.pdf-proxy]
verify_jwt = false

[functions.digistore24-ipn]
verify_jwt = false

[functions.digistore24-import]
verify_jwt = false
